apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: kube-public
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30042
      