apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-deployment
  namespace: kube-public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poll
  template:
    metadata:
      labels:
        app: poll
    spec:
      containers:
      - name: poll
        image: traefik:1.7
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
      restartPolicy: Always